
import React, { useState } from 'react';
import { Plus, MoreHorizontal, Image, Eye, Upload, Video, Globe, Trash2, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Badge } from '@/components/ui/badge';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';

interface Question {
  id: number;
  title: string;
  content: string;
  followUpType: string;
  media?: Array<{type: 'image' | 'video' | 'webpage', url: string, name: string}>;
}

const GuidingQuestions = () => {
  const [questions, setQuestions] = useState<Question[]>([
    {
      id: 1,
      title: "What were your initial impressions of the packaging and presentation?",
      content: "Gauge the user's first emotional and cognitive reactions upon receiving the TechFusion SmartWatch 2.0. This includes evaluating the visual appeal, perceived quality, and overall excitement generated by the packaging.",
      followUpType: "Surface scan (0-1 follow-ups)",
      media: [{type: 'image', url: "/lovable-uploads/2f07911a-86af-4ccd-a91d-84bf490a65c5.png", name: "packaging.png"}]
    },
    {
      id: 2,
      title: "How did you experience getting the watch out of the box?",
      content: "This question aims to understand any challenges the user may face during the unboxing process, such as difficult-to-open seals, tightly packed components, or unclear instructions. Insights from this question help identify potential improvements to ensure the unboxing experience is smooth and enjoyable, enhancing overall customer satisfaction.",
      followUpType: "Surface scan (0-1 follow-ups)",
      media: [{type: 'image', url: "/lovable-uploads/2f07911a-86af-4ccd-a91d-84bf490a65c5.png", name: "unboxing.png"}]
    },
    {
      id: 3,
      title: "Would you recommend this product to your friends or family? Why or why not?",
      content: "Add context to help the AI ask the right follow-ups",
      followUpType: "AI decides"
    }
  ]);

  const [showAddQuestion, setShowAddQuestion] = useState(false);
  const [newQuestion, setNewQuestion] = useState({
    title: '',
    content: '',
    followUpType: 'AI decides',
    media: [] as Array<{type: 'image' | 'video' | 'webpage', url: string, name: string}>
  });

  const addQuestion = () => {
    if (newQuestion.title.trim()) {
      setQuestions([...questions, {
        id: Date.now(),
        ...newQuestion
      }]);
      setNewQuestion({
        title: '',
        content: '',
        followUpType: 'AI decides',
        media: []
      });
      setShowAddQuestion(false);
    }
  };

  const removeQuestion = (id: number) => {
    setQuestions(questions.filter(q => q.id !== id));
  };

  const updateQuestion = (id: number, field: string, value: any) => {
    setQuestions(questions.map(q => 
      q.id === id ? { ...q, [field]: value } : q
    ));
  };

  const addMediaToQuestion = (questionId: number, mediaType: 'image' | 'video' | 'webpage') => {
    const mockUrl = mediaType === 'image' ? '/lovable-uploads/2f07911a-86af-4ccd-a91d-84bf490a65c5.png' : '#';
    const mockName = `${mediaType}_${Date.now()}`;
    
    setQuestions(questions.map(q => 
      q.id === questionId 
        ? { 
            ...q, 
            media: [...(q.media || []), {type: mediaType, url: mockUrl, name: mockName}]
          } 
        : q
    ));
  };

  const removeMediaFromQuestion = (questionId: number, mediaIndex: number) => {
    setQuestions(questions.map(q => 
      q.id === questionId 
        ? { 
            ...q, 
            media: q.media?.filter((_, index) => index !== mediaIndex) 
          } 
        : q
    ));
  };

  const saveQuestions = () => {
    console.log('Saving questions...', questions);
    // Add toast notification here
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold text-gray-900">Guiding questions</h2>
          <p className="text-gray-600">Write out your guiding questions that structure the interview and add context for each question to help the AI ask the right follow-ups</p>
        </div>
      </div>

      <div className="space-y-4">
        {questions.map((question, index) => (
          <Card key={question.id} className="border-l-4 border-l-blue-500">
            <CardHeader className="pb-4">
              <div className="flex items-start justify-between">
                <div className="flex items-start gap-4 flex-1">
                  <div className="w-8 h-8 bg-gradient-to-r from-blue-500 to-orange-500 text-white rounded flex items-center justify-center font-medium text-sm">
                    {index + 1}
                  </div>
                  <div className="flex-1">
                    <h3 className="font-medium text-gray-900 mb-2">Question {index + 1}</h3>
                    <Input 
                      value={question.title}
                      onChange={(e) => updateQuestion(question.id, 'title', e.target.value)}
                      className="font-medium text-gray-900 mb-3 focus:border-blue-500"
                      placeholder="Enter your question..."
                    />
                    
                    {/* Media Display */}
                    {question.media && question.media.length > 0 && (
                      <div className="flex flex-wrap gap-2 mb-3">
                        {question.media.map((media, mediaIndex) => (
                          <div key={mediaIndex} className="relative group">
                            {media.type === 'image' && (
                              <div className="w-16 h-16 rounded overflow-hidden bg-gray-100 relative">
                                <img src={media.url} alt={media.name} className="w-full h-full object-cover" />
                                <button 
                                  onClick={() => removeMediaFromQuestion(question.id, mediaIndex)}
                                  className="absolute -top-1 -right-1 bg-red-500 text-white rounded-full w-4 h-4 flex items-center justify-center text-xs opacity-0 group-hover:opacity-100 transition-opacity"
                                >
                                  <X className="w-2 h-2" />
                                </button>
                              </div>
                            )}
                            {media.type === 'video' && (
                              <div className="w-16 h-16 rounded bg-blue-100 flex items-center justify-center relative group">
                                <Video className="h-6 w-6 text-blue-600" />
                                <button 
                                  onClick={() => removeMediaFromQuestion(question.id, mediaIndex)}
                                  className="absolute -top-1 -right-1 bg-red-500 text-white rounded-full w-4 h-4 flex items-center justify-center text-xs opacity-0 group-hover:opacity-100 transition-opacity"
                                >
                                  <X className="w-2 h-2" />
                                </button>
                              </div>
                            )}
                            {media.type === 'webpage' && (
                              <div className="w-16 h-16 rounded bg-orange-100 flex items-center justify-center relative group">
                                <Globe className="h-6 w-6 text-orange-600" />
                                <button 
                                  onClick={() => removeMediaFromQuestion(question.id, mediaIndex)}
                                  className="absolute -top-1 -right-1 bg-red-500 text-white rounded-full w-4 h-4 flex items-center justify-center text-xs opacity-0 group-hover:opacity-100 transition-opacity"
                                >
                                  <X className="w-2 h-2" />
                                </button>
                              </div>
                            )}
                          </div>
                        ))}
                      </div>
                    )}

                    {/* Media Upload Buttons */}
                    <div className="flex gap-2 mb-3">
                      <Button 
                        variant="outline" 
                        size="sm"
                        onClick={() => addMediaToQuestion(question.id, 'image')}
                        className="text-blue-600 border-blue-200 hover:bg-blue-50"
                      >
                        <Image className="h-4 w-4 mr-1" />
                        Image
                      </Button>
                      <Button 
                        variant="outline" 
                        size="sm"
                        onClick={() => addMediaToQuestion(question.id, 'video')}
                        className="text-blue-600 border-blue-200 hover:bg-blue-50"
                      >
                        <Video className="h-4 w-4 mr-1" />
                        Video
                      </Button>
                      <Button 
                        variant="outline" 
                        size="sm"
                        onClick={() => addMediaToQuestion(question.id, 'webpage')}
                        className="text-orange-600 border-orange-200 hover:bg-orange-50"
                      >
                        <Globe className="h-4 w-4 mr-1" />
                        Webpage
                      </Button>
                    </div>
                  </div>
                  <div className="flex items-center gap-2">
                    <Select value={question.followUpType} onValueChange={(value) => updateQuestion(question.id, 'followUpType', value)}>
                      <SelectTrigger className="w-48">
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="Surface scan (0-1 follow-ups)">Surface scan</SelectItem>
                        <SelectItem value="In-depth analysis (2-4 follow-ups)">In-depth analysis</SelectItem>
                        <SelectItem value="AI decides">AI decides</SelectItem>
                      </SelectContent>
                    </Select>
                    <Button variant="ghost" size="sm" onClick={() => removeQuestion(question.id)}>
                      <Trash2 className="h-4 w-4 text-red-500" />
                    </Button>
                  </div>
                </div>
              </div>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Content</label>
                  <Textarea 
                    value={question.content}
                    onChange={(e) => updateQuestion(question.id, 'content', e.target.value)}
                    className="w-full min-h-[80px] focus:border-blue-500"
                    placeholder="Add context to help the AI ask the right follow-ups"
                  />
                </div>
              </div>
            </CardContent>
          </Card>
        ))}

        {showAddQuestion ? (
          <Card className="border-2 border-dashed border-blue-300 bg-blue-50">
            <CardContent className="p-6">
              <div className="space-y-4">
                <Input 
                  value={newQuestion.title}
                  onChange={(e) => setNewQuestion({...newQuestion, title: e.target.value})}
                  placeholder="Enter your question..."
                  className="font-medium focus:border-blue-500"
                />
                <Textarea 
                  value={newQuestion.content}
                  onChange={(e) => setNewQuestion({...newQuestion, content: e.target.value})}
                  placeholder="Add context to help the AI ask the right follow-ups"
                  className="min-h-[80px] focus:border-blue-500"
                />
                <div className="flex items-center gap-2">
                  <Select value={newQuestion.followUpType} onValueChange={(value) => setNewQuestion({...newQuestion, followUpType: value})}>
                    <SelectTrigger className="w-48">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="Surface scan (0-1 follow-ups)">Surface scan</SelectItem>
                      <SelectItem value="In-depth analysis (2-4 follow-ups)">In-depth analysis</SelectItem>
                      <SelectItem value="AI decides">AI decides</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                <div className="flex gap-2">
                  <Button onClick={addQuestion} className="bg-blue-500 hover:bg-blue-600">
                    Add Question
                  </Button>
                  <Button variant="outline" onClick={() => setShowAddQuestion(false)}>
                    Cancel
                  </Button>
                </div>
              </div>
            </CardContent>
          </Card>
        ) : (
          <Button 
            variant="outline" 
            className="w-full border-dashed border-blue-300 h-12 text-blue-600 hover:bg-blue-50"
            onClick={() => setShowAddQuestion(true)}
          >
            <Plus className="h-4 w-4 mr-2" />
            Add Question
          </Button>
        )}
      </div>

      {/* Save button at bottom */}
      <div className="pt-6 border-t border-gray-200">
        <Button 
          onClick={saveQuestions}
          className="bg-gradient-to-r from-blue-500 to-orange-500 hover:from-blue-600 hover:to-orange-600 text-white"
        >
          Save Questions
        </Button>
      </div>
    </div>
  );
};

export default GuidingQuestions;
